name: WEBSOCKET server CD

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy websocket server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST_IP}}
          key: ${{secrets.KEY}}
          username: ${{secrets.USERNAME}}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd /var/www/api.rtc-game.enyx.info/docroot
            git pull
            npm run tsc
            npm i
            pm2 start ecosystem.config.js
